# this is a helper file to run multiple containers by single command and mostly used in open source contributions

version: '3.6'
services:
  postgres:
    image: postgres #hub.docker.com
    ports: 
      - "5432:5432"
    environment:  # env variuables
      - "POSTGRES_USER: postgres"
      - "POSTGRES_DB: review"
      - "POSTGRES_PASSWORD: password"

  redis:
    image: redis
    ports:
      - "6379:6379"
